fix: file .yml

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -30,12 +30,27 @@ jobs:
           sudo apt-get install -y wget unzip xvfb
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
+
+          # Obtener versión de Chrome
           CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+")
+          CHROME_MAIN_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1-3)
           echo "Chrome version: $CHROME_VERSION"
-          wget -q "https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | cut -d '.' -f 1-3)/chromedriver_linux64.zip" -O chromedriver.zip
+          echo "Trying to download ChromeDriver for: $CHROME_MAIN_VERSION"
+
+          DRIVER_URL="https://chromedriver.storage.googleapis.com/$CHROME_MAIN_VERSION/chromedriver_linux64.zip"
+
+          # Validar existencia del archivo antes de descargar
+          if wget --spider $DRIVER_URL 2>/dev/null; then
+            wget -q $DRIVER_URL -O chromedriver.zip
+          else
+            echo "❌ Error: ChromeDriver not found for version $CHROME_MAIN_VERSION"
+            exit 1
+          fi
+
           unzip chromedriver.zip
           sudo mv chromedriver /usr/local/bin/chromedriver
           sudo chmod +x /usr/local/bin/chromedriver
+
 
       - name: Run tests
         run: |
